LibreChat-AI/librechat.ai

pages/docs/development/get_started.mdx

https://github.com/ayoub-fork/librechat.ai/pull/new/metion-mogodb

monodb is recommended in backend

---

pages/docs/configuration/librechat_yaml/setup.mdx

Indentation of yaml
use bind method

fix: setup.mdx

---

theme.config.tsx

fix: discord link

---

pages/docs/configuration/pre_configured_ai/google.mdx

Updating docs for this PR: https://github.com/danny-avila/LibreChat/pull/2782

Update Google / Vertex docs

---

pages/docs/configuration/stt_tts.mdx
pnpm-lock.yaml

docs update for https://github.com/danny-avila/LibreChat/pull/2836

📝 docs: STT/TTS

---

pages/docs/configuration/librechat_yaml/ai_endpoints/ollama.mdx

[docs]: Ollama yaml error - indent, spacing.

[docs]: Ollama yaml error fix

---

pages/changelog/config_v1.1.2.mdx
pages/changelog/config_v1.1.3.mdx
pages/docs/configuration/librechat_yaml/ai_endpoints/huggingface.mdx
pages/docs/configuration/librechat_yaml/ai_endpoints/mlx.mdx
pages/docs/configuration/pre_configured_ai/assistants.mdx
pages/docs/configuration/rag_api.mdx
pages/docs/configuration/stt_tts.mdx
pages/docs/remote/docker_linux.mdx

documentation update

---

pages/blog/2023-11-30_litellm.mdx
pages/docs/remote/traefik.mdx

[docs/config] Traefik - added ports, removed unnecessary network
[docs] new LLMs across AWS Bedrock, OpenAI, Azure, Google.

[docs/config] Traefik + [docs] new LLMs across AWS Bedrock, OpenAI, Azure, Google.

---

pages/docs/configuration/librechat_yaml/object_structure/custom_endpoint.mdx
pages/docs/configuration/librechat_yaml/object_structure/default_params.mdx

- Add notes on `addParams` usage
- Example for `max_tokens` in `addParams`
- Clarify `dropParams` functionality
- Note `default_params` immutability
- Update links to relevant sections

Enhance documentation to explain addParams and dropParams functionality

---

pages/docs/configuration/dotenv.mdx

Adjusting docs regarding changes [made in this PR](https://github.com/danny-avila/LibreChat/pull/2960).

Adjust footer docs matching new markdown links

---

pages/docs/configuration/dotenv.mdx

Documentation for PR https://github.com/danny-avila/LibreChat/pull/2469

Documentation for "Google tag manager integration"

---

pages/docs/configuration/tools/wolfram.mdx

- Added a new step in the documentation for Wolfram integration
This update is intended to guide users through the process of configuring their Wolfram API more effectively by providing clear instructions on selecting the correct API and copying the key

📝 docs: update Wolfram

---

pages/docs/user_guides/import_convos.mdx

removed a "Sharing on Discord" (duplicate of  `presets.mdx`)

📝 docs:  update `import_convos`

---

pages/docs/configuration/dotenv.mdx

I was about to submit PR for this issue: https://github.com/danny-avila/LibreChat/issues/1664
when I understood that the functionality is already available. All we need to do is to add options to mongo uri. So will just submit a doc update instead.

feat: 1664, mongo_uri

---

pages/docs/configuration/authentication/ldap.mdx

Document modification for the following PR:
[feat(LDAP): Add Flexible Configuration Options](https://github.com/danny-avila/LibreChat/pull/3124)

🚀 feat(LDAP): Add Attribute Mapping Settings

---

pages/docs/configuration/dotenv.mdx

Changes pertaining to title generation with Google models, per [Issue 1422](https://github.com/danny-avila/LibreChat/issues/1422)
- Add documentation for new `GOOGLE_TITLE_MODEL` environment variable

feat: Add titling to Google client

---

pages/docs/remote/railway.mdx

feat: add Railway signup referral link and update railway template referral code

🚀 feat: add Railway signup referral link and update railway template referral code

---

pages/docs/configuration/librechat_yaml/ai_endpoints/perplexity.mdx

Updated the list of available models as listed on the [perplexity docs](https://docs.perplexity.ai/docs/model-cards)

Update perplexity models

---

pages/docs/configuration/stt_tts.mdx

https://github.com/danny-avila/LibreChat/pull/3312

📝 docs: auto send text slider

---

pages/docs/configuration/dotenv.mdx
pages/docs/configuration/rag_api.mdx
pages/docs/documentation/index.mdx
pages/docs/remote/nginx.mdx
pages/docs/remote/traefik.mdx

Originally https://github.com/LibreChat-AI/librechat.ai/pull/95
Corresponding PR on the main repo: https://github.com/danny-avila/LibreChat/pull/3455
This updates the ENV config to address the new variables I added for the static cache. I put this right after ports in the Server Config section.
Additionally, I wasn't able to find this repo so I added that to the "[Contributing to the Docs](https://www.librechat.ai/docs/documentation)" page. 
Apparently, my auto-formatter fixed some extra trailing spaces as well. Sorry about that. 
This pull request includes several updates to the documentation to enhance clarity and provide additional configuration options. The most important changes include the addition of a new section on static file cache control, updates to the cache control behavior …

⚡ docs: Add static file configuration & update how to contribute

---

pages/docs/configuration/_meta.ts
pages/docs/local/_meta.ts
pages/docs/local/docker.mdx
pages/docs/local/helm_chart.mdx
pages/docs/local/index.mdx
pages/docs/local/npm.mdx

Accompanying LibreChat PR to include a helm chart in repo: https://github.com/danny-avila/LibreChat/pull/3539

🪖 feat: Helm Chart

---

pages/blog/2023-10-29_basic_auth.mdx

#111 Added proxy settings for BASIC authentication.

---

pages/docs/configuration/authentication/OAuth2-OIDC/authelia.mdx

I added a page for Authelia setup.

Docs add section for Authelia

---

pages/docs/configuration/dotenv.mdx

Noticed this typo when reading through the docs

fix type in dotenv.mdx

---

pages/docs/configuration/dotenv.mdx

https://github.com/danny-avila/LibreChat/pull/4565

🔃 feat: add configurable index.html cache headers

---

pages/docs/configuration/librechat_yaml/ai_endpoints/neurochain.mdx

We have successfully tested LibreChat with Neurochain.AI API, would like to have our configuration in the documentation.

Addidng NeurochainAI documentation neurochain.mdx

---

components/Author/AuthorPage.tsx
components/home/components/HomeSection.tsx
components/ui/accordion.tsx
components/ui/avatar.tsx
components/ui/dialog.tsx
components/ui/dropdown-menu.tsx
components/ui/form.tsx
components/ui/label.tsx
components/ui/select.tsx
components/ui/tabs.tsx
pages/docs/configuration/dotenv.mdx
pages/docs/configuration/token_usage.mdx

originally https://github.com/LibreChat-AI/librechat.ai/pull/156

🪙 feat: automatically add start balance

---

pages/docs/configuration/dotenv.mdx
pages/docs/configuration/token_usage.mdx

Add documentation for https://github.com/danny-avila/LibreChat/pull/4506.

feat: Set balance for user

---

pages/docs/configuration/librechat_yaml/setup.mdx

📘 fix: broken link in LibreChat YAML configuration

---

pages/docs/configuration/tools/index.mdx
pages/docs/configuration/tools/openweather.mdx

📘 docs: add OpenWeather plugin configuration and usage instructions

---

pages/docs/configuration/authentication/OAuth2-OIDC/_meta.ts
pages/docs/configuration/authentication/OAuth2-OIDC/apple.mdx
pages/docs/configuration/authentication/OAuth2-OIDC/index.mdx

added Apple OAuth2 login Doc.
regarding this merge request: https://github.com/danny-avila/LibreChat/pull/5473

🍎 feat: Apple auth

---

pages/docs/features/index.mdx
pages/docs/features/temporary_chat.mdx

Document the "Temporary Chats" feature newly implemented on these PRs:
https://github.com/danny-avila/LibreChat/pull/5493
https://github.com/danny-avila/LibreChat/pull/5705

📝 docs: Add documentation about Temporary Chats feature.

---

pages/docs/development/tools_and_plugins.mdx

Description
The old link was moved so this PR updates it.

🔗 fix: broken link in tools_and_plugins.mdx

---

pages/docs/configuration/pre_configured_ai/openai.mdx

I struggled a long time with this, thinking something was wrong with my install.
I think this would be helpful to have mentioned here.
Source: https://github.com/danny-avila/LibreChat/discussions/1682#discussioncomment-8310689

Clarify visibility of "new" models.

---

pages/docs/configuration/dotenv.mdx

As described over [here](https://github.com/danny-avila/LibreChat/pull/6066)

docs: Adding documentation for OIDC Auto-Redirect #5683

---

pages/docs/features/url_query.mdx

Related to feature: https://github.com/danny-avila/LibreChat/pull/6440

Update URL Param section to include automatic submit example

---

pages/docs/configuration/tools/flux.mdx
pages/docs/configuration/tools/index.mdx

related to: https://github.com/danny-avila/LibreChat/pull/5410

🌊 docs: Flux

---

components/changelog/content/v0.7.7-rc1.mdx
components/changelog/content/v0.7.8-rc1.mdx
pages/_meta.ts
pages/changelog/v0.7.7-rc1.mdx
pages/changelog/v0.7.8-rc1.mdx
pages/docs/configuration/librechat_yaml/object_structure/mcp_servers.mdx
pages/docs/features/agents.mdx
pages/pricing.mdx

Also adds details on MCP Headers config and missing v0.7.7-rc1 changelog

✨ v0.7.8-rc1

---

pages/docs/configuration/librechat_yaml/object_structure/_meta.ts
pages/docs/configuration/librechat_yaml/object_structure/custom_params.mdx

Feature coming from this [discussion](https://github.com/danny-avila/LibreChat/discussions/7185)
Relevant PR on LibreChat: https://github.com/danny-avila/LibreChat/pull/7342

feat: Customize Endpoint Parameters

---

.cursor/rules/librechat-documentation.mdc
components/changelog/content/config_v1.2.8.mdx
pages/changelog/config_v1.2.8.mdx
pages/docs/configuration/cdn/azure.mdx
pages/docs/configuration/cdn/firebase.mdx
pages/docs/configuration/cdn/s3.mdx
pages/docs/configuration/librechat_yaml/example.mdx
pages/docs/configuration/librechat_yaml/object_structure/config.mdx
pages/docs/configuration/librechat_yaml/object_structure/memory.mdx
pages/docs/configuration/librechat_yaml/object_structure/ocr.mdx
pages/docs/configuration/token_usage.mdx
pages/docs/features/memory.mdx
pages/docs/features/ocr.mdx
pages/docs/quick_start/custom_endpoints.mdx
pages/docs/remote/docker_linux.mdx

- Updated version numbers in multiple configuration files to reflect the new version 1.2.8.
- Introduced a new `azure_mistral_ocr` strategy option for OCR configuration, enabling the use of Mistral OCR models deployed on Azure AI Foundry.
- Enhanced documentation for OCR configuration to include details on Azure deployment and its requirements.
- Added changelog entries for version 1.2.8, summarizing the new features and updates.

📚 docs: Update Config to v1.2.8 and add Azure Mistral OCR Support

---

components/CardIcons/Roadmap.tsx
components/FooterMenu.tsx
pages/docs/index.mdx

On the homepage of the docs there was a link to the 2024 Roadmap, updated to 2025

Update link to 2024 Roadmap to 2025 Roadmap

---

pages/docs/configuration/librechat_yaml/object_structure/mcp_servers.mdx
pages/docs/features/mcp.mdx

Related to https://github.com/danny-avila/LibreChat/pull/8718

🗃️ docs: Update MCP docs for new settings panel behavior and to clarify configuration/initialization steps for servers like github-mcp

---

pages/docs/configuration/librechat_yaml/ai_endpoints/truefoundry.mdx

-Adding Truefoundry AI Gateway inside ai_endpoints
About Truefoundry:
[TrueFoundry](https://www.truefoundry.com/) is a Kubernetes-native, cloud-agnostic PaaS that empowers enterprise AI/ML teams to build, deploy, and manage LLM applications securely and efficiently on cloud or on-prem infrastructure. It also ensures unified access control via its AI Gateway, and cost-aware dev‑ops for GenAI workloads—all through developer-friendly APIs and UI.

🤖 docs: Add Truefoundry Custom Endpoint Example
