- pages/docs/configuration/librechat_yaml/object_structure/file_config.mdx
The link to the RAG API page was broken.
> Fix RAG API link

- pages/docs/configuration/librechat_yaml/ai_endpoints/azure.mdx
There are now many more serverless models available in Azure AI Studio. I updated the docs to
- Show how to filter the model catalog to show available models
- Add an additional example model card
- Add a example config for phi-3
> Add Azure serverless examples

- pages/docs/configuration/librechat_yaml/object_structure/model_specs.mdx
- Updated to real-world example
- Added `model`
- Additional example for `promptPrefix`
- Updated `greeting`
- Added link to interface page
> Add missing keys and new example to modelSpec

- pages/docs/development/translation.mdx
There's an additional `General` folder missing in the URLs.
> 📝 docs: fix path of General.tsx in development/translation.mdx

- pages/docs/configuration/dotenv.mdx
There are currently two `#### DALL-E:`, much the second one should be `#### DALL-E (Azure):` I believe.
> 📝 docs: remove duplicated heading `DALL-E:` in configuration/dotenv.mdx 

- pages/docs/configuration/authentication/ldap.mdx
This patch corresponds to #3268 which allows for LDAP login via username instead of email address.
> Allow username for LDAP login

- pages/docs/configuration/authentication/ldap.mdx
- pages/docs/configuration/dotenv.mdx
This PR updates the documentation for https://github.com/danny-avila/LibreChat/pull/3247 which allows configuration to disable ldap tls.
> docs: ldap tls config

- pages/docs/configuration/librechat_yaml/ai_endpoints/togetherai.mdx
Add a python script to fetch together.ai models for librechat.yml
> Add python script to fetch togetherai models

- pages/cookie.mdx
- pages/privacy.mdx
- pages/tos.mdx
I was searching for "update" keyword to look for instructions to update the librechat deployment but found it strange that the privacy policy is the first result.
I think it shouldn't be indexed/searchable to start with, to avoid cluttering search results from the actual docs pages.
> Omit Privacy and TOS pages from search

- pages/docs/configuration/librechat_yaml/ai_endpoints/shuttleai.mdx
Pretty straight-forward - just updating outdated models to its latest versions.
> Update ShuttleAI default models

- pages/docs/configuration/librechat_yaml/object_structure/interface.mdx
Changed interface docs to support the new feature for which I sent a PR earlier.
https://github.com/danny-avila/LibreChat/pull/3712
> ⚖️ feat: Terms and Conditions Dialog

- pages/docs/configuration/librechat_yaml/ai_endpoints/shuttleai.mdx
Switched domain from `shuttleai.app` to `shuttleai.com`. (Both work, however `.com` is now encouraged.)
> Update ShuttleAI 🚀

- pages/docs/configuration/authentication/OAuth2-OIDC/authentik.mdx
Added initial [Authentik](https://github.com/goauthentik/authentik) documentation. 
Currently "guides" are scattered across Discord and issues. Followed the Keycloak guide and adapted it for Authentik. Can probably be improved by adding images and tidying up the formatting and verbosity.
> docs: add Authentik documentation

- pages/docs/configuration/authentication/ldap.mdx
See https://github.com/danny-avila/LibreChat/pull/4127
> feat: Allow other LDAP field besides "mail" to map to email address

- pages/docs/configuration/rag_api.mdx
Currently, there isn't documentation that highlights the ability to use full context of the documents uploaded for RAG. This causes new users like myself to run into subpar RAG results in certain scenarios. Adding documentation for the RAG_USE_FULL_CONTEXT parameter/variable to raise awareness of this feature.
Related discussion: https://github.com/danny-avila/LibreChat/discussions/4066
> RAG API Documentation Update: added explanation for RAG_USE_FULL_CONTEXT variable

- pages/docs/configuration/librechat_yaml/ai_endpoints/portkey.mdx
This PR introduces new documentation explaining how to use Portkey's custom endpoints with LibreChat-AI. Key additions include:
- How to update librechat.yaml file to integrate with Portkey
@danny-avila
> Add Portkey Custom Endpoints Docs

- pages/docs/user_guides/artifacts.mdx
I put LibreChat on a VPS and was trying out the Artifacts feature but noticed the apps wouldn't load. The right panel would show:
```
"This content is blocked. Contact the site owner to fix the issue."
``` 
and then
```
Couldn't connect to server
This means sandpack cannot connect to the runtime or your network is having some issues. Please check the network tab in your browser and try again. If the problem persists, report it via email or submit an issue on GitHub.
ENV: create-react-app
ERROR: TIME_OUT
```
Checking network tab in Chrome dev tools I was seeing:
```
Refused to frame 'https://2-18-2-sandpack.codesandbox.io/' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a …
```
> Content-Security-Policy and loading HTML apps with Artifacts

- pages/docs/configuration/authentication/OAuth2-OIDC/azure.mdx
…kind is required
`OPENID_REQUIRED_ROLE_TOKEN_KIND` is required and the way the old docs were written, seemed to indicate that it was only necessary if you want to restrict access by groups. I was getting an Internal Server Error after logging in with Open ID if this environment variable was not set. Once I added it, I was able to log in successfully.
Closes #190
> 📘 docs: Update Azure OAuth2 to Clarify Variable Requirement

- pages/docs/configuration/librechat_yaml/object_structure/file_config.mdx
Fix the outdated link for openai assistants tools support file types
> 📂 docs: outdated link for openai assistants tools support file types

- pages/docs/configuration/authentication/OAuth2-OIDC/github.mdx
- pages/docs/configuration/dotenv.mdx
https://github.com/danny-avila/LibreChat/pull/5621
> 🏢 docs: GitHub Enterprise Auth SSO

- pages/docs/development/tools_and_plugins.mdx
> Fixed Typo: Update tools_and_plugins.mdx

- pages/docs/configuration/authentication/OAuth2-OIDC/azure.mdx
Added the variable to ensure the OpenID SSO button appears. If the value is set to false, it will not appear.
> Visible SSO button

- pages/docs/configuration/pre_configured_ai/assistants.mdx
- pages/docs/features/agents.mdx
Replaces: https://github.com/LibreChat-AI/librechat.ai/pull/162
Add section for agents actions
> 🔨 feat: Use `x-strict` attribute in OpenAPI Actions for Strict Function Definition

- pages/docs/configuration/dotenv.mdx
- pages/docs/configuration/librechat_yaml/object_structure/interface.mdx
[#5870](https://github.com/danny-avila/LibreChat/pull/5870)
> feat: Add Custom Welcome Message Support in LibreChat

- pages/docs/configuration/authentication/ldap.mdx
- pages/docs/configuration/dotenv.mdx
PR: https://github.com/danny-avila/LibreChat/pull/6438
This pull request includes updates to the LDAP authentication documentation in the `pages/docs/configuration` directory. The changes include corrections to the spelling of "LibreChat" and the addition of a new feature for LDAP StartTLS.
Documentation updates:
* [`pages/docs/configuration/authentication/ldap.mdx`](diffhunk://#diff-0c02dc7f7c676aa75fcf818bfe579a288a941abf8e4b671a39af50e202a82730L34-R34): Corrected the spelling of "LibreChat" in multiple instances. [[1]](diffhunk://#diff-0c02dc7f7c676aa75fcf818bfe579a288a941abf8e4b671a39af50e202a82730L34-R34) [[2]](diffhunk://#diff-0c02dc7f7c676aa75fcf818bfe579a288a941abf8e4b671a39af50e202a82730L86-R86)
* [`pages/docs/configuration/authentication/ldap.mdx`](diffhunk://#diff-0c02dc7f7c676a …
> feat: Add support for LDAP StartTLS and update documentation for LDAP settings

- pages/docs/configuration/librechat_yaml/object_structure/_meta.ts
- pages/docs/configuration/librechat_yaml/object_structure/balance.mdx
- pages/docs/configuration/librechat_yaml/object_structure/interface.mdx
- pages/docs/configuration/token_usage.mdx
This pull request introduces comprehensive changes to the documentation and configuration for managing token credit balances in LibreChat. The primary focus is on adding a new `balance` object structure and updating the token usage documentation to reflect these changes.
* [`pages/docs/configuration/librechat_yaml/object_structure/_meta.ts`](diffhunk://#diff-27966d15fc4268b8c5505786a767f8c986c21abd3c9465f554b859c74e205eeeR7): Added `balance` to the list of configuration objects.
* [`pages/docs/configuration/librechat_yaml/object_structure/balance.mdx`](diffhunk://#diff-19705447a3a05a488faf35ada1497be776603c541a43a8d426ec23b6b00cc56dR1-R158): Created a new document detailing the `balance` object, which includes fields like `enabled`, `startBalance`, `autoRefillEnabled`, …
> feat: Add balance management configuration to YAML and update token usage documentation

- pages/docs/configuration/cdn/s3.mdx
This commit updates the documentation related to S3 storage configuration to include the `AWS_ENDPOINT_URL` environment variable. This variable was introduced in PR [#6431](https://github.com/danny-avila/LibreChat/pull/6431) to allow users to specify a custom endpoint URL for S3 connections, but the documentation is not update.
The changes include:
- Adding a description for `AWS_ENDPOINT_URL`, clarifying its purpose and indicating that it's optional.
> docs: Document AWS_ENDPOINT_URL for S3 configuration

- pages/docs/configuration/dotenv.mdx
The example for TRUST_PROXY was using HOST, apparently an older version?
> docs: Corrected example for TRUST_PROXY

- pages/docs/configuration/librechat_yaml/object_structure/mcp_servers.mdx
- pages/docs/features/agents.mdx
- Updated the `mcp_servers.mdx` and `agents.mdx` files to include dynamic user field placeholders for headers, URLs, and environment variables.
- Added detailed descriptions and examples for user field placeholders such as `{{LIBRECHAT_USER_EMAIL}}`, `{{LIBRECHAT_USER_ROLE}}`, and others.
- Improved clarity on the usage of environment variables and their integration with user-specific data.
> 📚 docs: MCP server Dynamic User Field Placeholders

- pages/docs/configuration/librechat_yaml/object_structure/config.mdx
- pages/docs/configuration/librechat_yaml/object_structure/mcp_servers.mdx
Adds documentation for the new `serverInstructions` configuration option for MCP servers, which allows automatic injection of contextual instructions into agent system messages. https://github.com/danny-avila/LibreChat/pull/7660
- **config.mdx**: Added `serverInstructions` to the MCP servers configuration overview with examples
- **mcp_servers.mdx**: Added documentation for the `serverInstructions` parameter including:
- Parameter documentation with type, description, and options
- Usage guidance for when to use each configuration option
- Examples showing different serverInstructions configurations
- Additional information section explaining how server instructions work
- Server using server-provided instructions (`serverInstructions: true`)
- Server with custom multiline instructions …
> Add serverInstructions configuration for MCP servers

- pages/docs/configuration/librechat_yaml/object_structure/config.mdx
This PR adds comprehensive documentation for the new `clientSideImageResize` configuration feature in LibreChat. This feature enables automatic client-side image resizing before upload to optimize file handling and prevent upload errors.
- **Added `clientSideImageResize` to fileConfig subkeys table** - Listed as a new configuration option under the main `fileConfig` section
- **Dedicated section for `clientSideImageResize`** - Complete documentation with:
- Key definition and purpose
- Comprehensive subkeys table documenting all 5 configuration options:
- `enabled` - Boolean to enable/disable the feature
- `maxWidth` - Maximum width in pixels (default: 1920)
- `maxHeight` - Maximum height in pixels (default: 1080)
- `quality` - JPEG compression quality 0.1-1.0 (default: 0.8)
- …
> docs: add clientImageResize configuration documentation

- components/changelog/content/config_v1.2.8.mdx
- pages/docs/configuration/librechat_yaml/object_structure/model_specs.mdx
- pages/docs/features/url_query.mdx
This pull request updates the documentation for newly added fields / toggles in the Parameters Panel.
* Improved the [Model Specs documentation](/docs/configuration/librechat_yaml/object_structure/model_specs) to include updates on parameter support, such as `disableStreaming`, `thinking`, `thinkingBudget`, `web_search`, and others.
* Updated default values for existing parameters in `preset`:
- Changed the default for `resendFiles` from `false` to `true`.
- Added a default value of `"auto"` for `imageDetail`.
- Set the default for `thinking` to `true`.
* Added new parameters to the `preset` configuration:
- [`reasoning_effort`](diffhunk://#diff-b685020308b775b3c8a09bf011506c8d40b6d3f04337ad4bdf008456459780caR725-R878): Controls the reasoning effort level for the model, with accepted …
> 📚 docs: Update Preset Fields and Query Params

- pages/docs/configuration/dotenv.mdx
Documentation for the new environment variable added in
- https://github.com/danny-avila/LibreChat/pull/8307
> 📚 docs: Add documentation for `ENABLE_IMAGE_OUTPUT_GZIP_SCAN` environment variable

- components/changelog/content/config_v1.2.8.mdx
- pages/docs/configuration/librechat_yaml/object_structure/web_search.mdx
This pull request adds documentation for the new firecrawlOptions field in the `webSearch` `librechat.yaml` configuration.
* **New Firecrawl scraper options:** Added the set of configuration options available for the Firecrawl scraper: `formats`, `includeTags`, `excludeTags`, `headers`, `waitFor`, `timeout`, `maxAge`, `mobile`, `skipTlsVerification`, `parsePDF`, `removeBase64Images`, `blockAds`, `storeInCache`, `zeroDataRetention`, `onlyMainContent`, `location`, and `changeTrackingOptions`. Included link to Firecrawl API documentation for more detailed descriptions and default values for available options. [[1]](diffhunk://#diff-d6d57f012e476e1d831e224e9ac6a2ad2618edce241183e7a853580fa9d50cb1R26-R28) [[2]](diffhunk://#diff-20fdb3d8beac92dec15501d6d7f7a24739c62acc9d755bec8b8ef4beb93a3d6eR10 …
> 📚 docs: Add firecrawlOptions to web_search

- pages/docs/configuration/librechat_yaml/object_structure/mcp_servers.mdx
- pages/docs/features/mcp.mdx
- Added `startup` field to MCP server configuration documentation, explaining how users can now control server connection at application startup.
- Added instructions for reinitializing MCP servers with user credentials from within the UI.
> 📚 docs: Add MCP reinitialization instructions and document new 'startup' property for MCP servers

- components/changelog/content/config_v1.2.8.mdx
- pages/docs/configuration/librechat_yaml/object_structure/config.mdx
- pages/docs/configuration/librechat_yaml/object_structure/file_config.mdx
- Added `stt` configuration to `fileConfig` for Speech-to-Text audio file processing, including supported MIME types.
- Updated changelog to reflect the addition of STT alongside existing OCR and text parsing configurations.
Related to [#8893](https://github.com/danny-avila/LibreChat/pull/8893)
> 📚 docs: Add STT Config Documentation

- pages/docs/configuration/stt_tts.mdx
Hi, while reading about how to configure the [speech settings](https://www.librechat.ai/docs/configuration/stt_tts#openai-compatible), I found a typo that I fixed.
- `switcg` → `switch`
> fix: Minor typo in stt_tts.mdx

- pages/docs/remote/nginx.mdx
It's not as straightforward to renew certbot when running nginx. 
Adding instructions to renew certificates.
> docs: instructions for renewing certbot when using nginx

- pages/docs/features/web_search.mdx
Current link: `https://serper.dev/api-key` results in a 404 not found. Updated to `https://serper.dev`
> Update broken link for Serper.dev in documentation
